//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import PKHUD

protocol ___FILEBASENAMEASIDENTIFIER___ViewControllerInput: class
{
    func displaySomething(viewModel: ViewModel<___FILEBASENAMEASIDENTIFIER___ViewModel>)
}

protocol ___FILEBASENAMEASIDENTIFIER___ViewControllerOutput
{
    func doSomething(request: ___FILEBASENAMEASIDENTIFIER___Request)
}

class ___FILEBASENAMEASIDENTIFIER___ViewController: UICollectionViewController, ___FILEBASENAMEASIDENTIFIER___ViewControllerInput
{
    // MARK: Clean Swift
    var output: ___FILEBASENAMEASIDENTIFIER___ViewControllerOutput!
    var router: ___FILEBASENAMEASIDENTIFIER___Router!

    // MARK: <#Feature#>
}

// MARK: - View Controller
extension ___FILEBASENAMEASIDENTIFIER___ViewController{
    // MARK: Object lifecycle
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ___FILEBASENAMEASIDENTIFIER___Configurator.sharedInstance.configure(self)
    }
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
}

// MARK: - <#Feature#>
extension ___FILEBASENAMEASIDENTIFIER___ViewController{
    // MARK: Setup

    // MARK: Load
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
        let request = ___FILEBASENAMEASIDENTIFIER___Request()
        output.doSomething(request)
    }
    
    // MARK: Display
    func displaySomething(viewModel: ViewModel<___FILEBASENAMEASIDENTIFIER___ViewModel>)
    {
        switch viewModel {
        case .Error(let error):
            PKHUD.sharedHUD.contentView = PKHUDTextView(text: error.localizedDescription)
            PKHUD.sharedHUD.show()
            PKHUD.sharedHUD.hide(afterDelay: 2.0)
            break

        case .Result(let result):
             
            break
        }
    }
}

