//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

let ___FILEBASENAMEASIDENTIFIER___PresenterErrorDomain = "___FILEBASENAMEASIDENTIFIER___Presenter"
enum ___FILEBASENAMEASIDENTIFIER___PresenterError: ErrorType {
    case General
}


class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___PresenterInput
{
    weak var output: ___FILEBASENAMEASIDENTIFIER___PresenterOutput!
    
    // MARK: - Presentation logic
    func presentSomething(response: Response<___FILEBASENAMEASIDENTIFIER___Response>)
    {
        switch response {
        case .Error(let error):
            output.<#display#>(ViewModel.Error(error))
            break
        case .Result(let result):
            let viewModel = <#viewModelFromDictonary(result.)#>
            output.<#display#>(ViewModel.Result(viewModel))
            break
        }
    }
}
