//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ___FILEBASENAMEASIDENTIFIER___Request
{
}

struct ___FILEBASENAMEASIDENTIFIER___Response
{
}

class ___FILEBASENAMEASIDENTIFIER___ViewModel: Mappable
{


    class func viewModelFromDictonary(dictonary: [String: AnyObject]) -> ___FILEBASENAMEASIDENTIFIER___ViewModel? {
        return Mapper<___FILEBASENAMEASIDENTIFIER___ViewModel>().map(dictonary)
    }

    required init?(_ map: Map) {
    }
    func mapping(map: Map) -> () {
         
    }
}

